/**
 * Auto-generated by scripts/write-config.mjs — do not commit.
 */
export const config = {
  siteAccessMode: "live",
  supabaseUrl: "https://xklkysmakrmgtiztsqug.supabase.co",
  supabasePublishableKey: "sb_publishable_bc7rST-Xjb6Ln4X1uoD6Jw_91jGmxZH",
  submitBuildUrl: "https://xklkysmakrmgtiztsqug.supabase.co/functions/v1/submit-build",
  adminBuildsUrl: "https://xklkysmakrmgtiztsqug.supabase.co/functions/v1/admin-builds",
  adminReportsUrl: "https://xklkysmakrmgtiztsqug.supabase.co/functions/v1/admin-reports",
  siteAccessUrl: "https://xklkysmakrmgtiztsqug.supabase.co/functions/v1/site-access",
  voteBuildUrl: "https://xklkysmakrmgtiztsqug.supabase.co/functions/v1/vote-build",
  createCheckoutUrl: "https://xklkysmakrmgtiztsqug.supabase.co/functions/v1/create-checkout",
  createPortalUrl: "https://xklkysmakrmgtiztsqug.supabase.co/functions/v1/create-portal",
  reportSimUrl: "https://xklkysmakrmgtiztsqug.supabase.co/functions/v1/report-sim",
  screenshotToBuildUrl: "https://xklkysmakrmgtiztsqug.supabase.co/functions/v1/screenshot-to-build",
  discordGuildUrl: "https://xklkysmakrmgtiztsqug.supabase.co/functions/v1/discord-guild",
  cosmeticCatalogUrl: "https://xklkysmakrmgtiztsqug.supabase.co/functions/v1/cosmetic-catalog",
  cosmeticSubmissionsUrl: "https://xklkysmakrmgtiztsqug.supabase.co/functions/v1/cosmetic-submissions",
};
