/**
 * GENERATED by scripts/gen-sim-dedicated-ports.mjs — do not hand-edit.
 * Raise fidelity via scripts/ports.js + registry REVIEWED, then re-run generator.
 */

import { HANDLERS } from '../handlers.js';

/** @param {string} id @param {string} family @param {string} template */
function stub(id, family, template) {
  const base = HANDLERS[template] || HANDLERS.basic_cd;
  return {
    handlerId: id,
    family,
    onCombatStart: base.onCombatStart,
    onCooldownEffect: base.onCooldownEffect,
  };
}

/** Band J — On-hit weapons: on_hit family (72 items) */
/** @type {Record<string, import('../handlers.js').ScriptHandler>} */
export const HANDLERS_J = {
  "amethyst_whelp": stub("amethyst_whelp", "on_hit", "start_regen"), // reviewed · Exclusive/AmethystWhelp.gd
  "automanaton": stub("automanaton", "on_hit", "basic_cd"), // reviewed · Exclusive/Automanaton.gd
  "axe": stub("axe", "on_hit", "basic_cd"), // reviewed · Exclusive/Axe.gd
  "bazooka": stub("bazooka", "on_hit", "basic_cd"), // reviewed · Exclusive/Bazooka.gd
  "big_bloodthorne": stub("big_bloodthorne", "on_hit", "poison_weapon"), // reviewed · Exclusive/BigBloodthorne.gd
  "bloodthorne": stub("bloodthorne", "on_hit", "poison_weapon"), // reviewed · Bloodthorne.gd
  "bloody_dagger": stub("bloody_dagger", "on_hit", "poison_weapon"), // reviewed · BloodyDagger.gd
  "boomerang": stub("boomerang", "on_hit", "basic_cd"), // reviewed · Exclusive/Boomerang.gd
  "brass_knuckles": stub("brass_knuckles", "on_hit", "basic_cd"), // reviewed · Exclusive/BrassKnuckles.gd
  "broom": stub("broom", "on_hit", "basic_cd"), // reviewed · Broom.gd
  "burning_blade": stub("burning_blade", "on_hit", "basic_cd"), // reviewed · Exclusive/BurningBlade.gd
  "burning_sword": stub("burning_sword", "on_hit", "basic_cd"), // reviewed · Exclusive/BurningSword.gd
  "chain_whip": stub("chain_whip", "on_hit", "basic_cd"), // reviewed · Exclusive/ChainWhip.gd
  "chainsaw": stub("chainsaw", "on_hit", "basic_cd"), // reviewed · Exclusive/Chainsaw.gd
  "claws_of_attack": stub("claws_of_attack", "on_hit", "basic_cd"), // reviewed · ClawsofAttack.gd
  "critwood_staff": stub("critwood_staff", "on_hit", "basic_cd"), // reviewed · CritwoodStaff.gd
  "cupcake_dragon": stub("cupcake_dragon", "on_hit", "basic_cd"), // reviewed · Exclusive/CupcakeDragon.gd
  "cupcake_staff": stub("cupcake_staff", "on_hit", "basic_cd"), // reviewed · Exclusive/CupcakeStaff.gd
  "cursed_dagger": stub("cursed_dagger", "on_hit", "poison_weapon"), // reviewed · CursedDagger.gd
  "daggerang": stub("daggerang", "on_hit", "poison_weapon"), // reviewed · Exclusive/Daggerang.gd
  "darksaber": stub("darksaber", "on_hit", "basic_cd"), // reviewed · Darksaber.gd
  "double_axe": stub("double_axe", "on_hit", "basic_cd"), // reviewed · Exclusive/DoubleAxe.gd
  "dragon_knight": stub("dragon_knight", "on_hit", "basic_cd"), // reviewed · Exclusive/DragonKnight.gd
  "eggscalibur": stub("eggscalibur", "on_hit", "basic_cd"), // reviewed · Eggscalibur.gd
  "emerald_whelp": stub("emerald_whelp", "on_hit", "start_regen"), // reviewed · Exclusive/EmeraldWhelp.gd
  "fancy_fencing_rapier": stub("fancy_fencing_rapier", "on_hit", "basic_cd"), // reviewed · FancyFencingRapier.gd
  "flame_whip": stub("flame_whip", "on_hit", "basic_cd"), // reviewed · Exclusive/FlameWhip.gd
  "forest_dragon": stub("forest_dragon", "on_hit", "basic_cd"), // reviewed · Exclusive/ForestDragon.gd
  "frostbite": stub("frostbite", "on_hit", "basic_cd"), // reviewed · Exclusive/Frostbite.gd
  "halberd": stub("halberd", "on_hit", "basic_cd"), // reviewed · Exclusive/Halberd.gd
  "hammer": stub("hammer", "on_hit", "basic_cd"), // reviewed · Hammer.gd
  "ice_dragon": stub("ice_dragon", "on_hit", "basic_cd"), // reviewed · Exclusive/IceDragon.gd
  "jynx_staff": stub("jynx_staff", "on_hit", "basic_cd"), // reviewed · Exclusive/JynxStaff.gd
  "katana": stub("katana", "on_hit", "basic_cd"), // reviewed · Exclusive/Katana.gd
  "lightning_staff": stub("lightning_staff", "on_hit", "basic_cd"), // reviewed · Exclusive/LightningStaff.gd
  "long_spear": stub("long_spear", "on_hit", "basic_cd"), // reviewed · Exclusive/LongSpear.gd
  "lucky_shortbow": stub("lucky_shortbow", "on_hit", "poison_weapon"), // reviewed · Exclusive/LuckyShortbow.gd
  "magic_staff": stub("magic_staff", "on_hit", "basic_cd"), // reviewed · MagicStaff.gd
  "magic_torch": stub("magic_torch", "on_hit", "basic_cd"), // reviewed · MagicTorch.gd
  "manathirst": stub("manathirst", "on_hit", "basic_cd"), // reviewed · Manathirst.gd
  "molten_dagger": stub("molten_dagger", "on_hit", "poison_weapon"), // reviewed · Exclusive/MoltenDagger.gd
  "molten_greatsword": stub("molten_greatsword", "on_hit", "basic_cd"), // reviewed · Exclusive/MoltenGreatsword.gd
  "molten_spear": stub("molten_spear", "on_hit", "basic_cd"), // reviewed · Exclusive/MoltenSpear.gd
  "molten_spear2": stub("molten_spear2", "on_hit", "basic_cd"), // reviewed · Exclusive/MoltenSpear2.gd
  "null_blade": stub("null_blade", "on_hit", "basic_cd"), // reviewed · Exclusive/NullBlade.gd
  "onion_cutter": stub("onion_cutter", "on_hit", "basic_cd"), // reviewed · Exclusive/OnionCutter.gd
  "poison_dagger": stub("poison_dagger", "on_hit", "poison_weapon"), // reviewed · PoisonDagger.gd
  "poison_shortbow": stub("poison_shortbow", "on_hit", "poison_weapon"), // reviewed · Exclusive/PoisonShortbow.gd
  "prismatic_sword": stub("prismatic_sword", "on_hit", "basic_cd"), // reviewed · Exclusive/PrismaticSword.gd
  "pumpkin": stub("pumpkin", "on_hit", "basic_cd"), // reviewed · Pumpkin.gd
  "rib_saw_blade": stub("rib_saw_blade", "on_hit", "basic_cd"), // reviewed · RibSawBlade.gd
  "ruby_chonk": stub("ruby_chonk", "on_hit", "basic_cd"), // reviewed · RubyChonk.gd
  "sapphire_whelp": stub("sapphire_whelp", "on_hit", "start_regen"), // reviewed · Exclusive/SapphireWhelp.gd
  "scissorswords": stub("scissorswords", "on_hit", "basic_cd"), // reviewed · Exclusive/Scissorswords.gd
  "serpent_staff": stub("serpent_staff", "on_hit", "basic_cd"), // reviewed · Exclusive/SerpentStaff.gd
  "shovel": stub("shovel", "on_hit", "basic_cd"), // reviewed · Shovel.gd
  "snow_stick": stub("snow_stick", "on_hit", "basic_cd"), // reviewed · Exclusive/SnowStick.gd
  "spectral_dagger": stub("spectral_dagger", "on_hit", "poison_weapon"), // reviewed · SpectralDagger.gd
  "spiked_staff": stub("spiked_staff", "on_hit", "basic_cd"), // reviewed · Exclusive/SpikedStaff.gd
  "squirrel_archer": stub("squirrel_archer", "on_hit", "basic_cd"), // reviewed · Exclusive/SquirrelArcher.gd
  "staff_of_fire": stub("staff_of_fire", "on_hit", "basic_cd"), // reviewed · Exclusive/StaffofFire.gd
  "stone": stub("stone", "on_hit", "basic_cd"), // reviewed · Stone.gd
  "stone_golem": stub("stone_golem", "on_hit", "basic_cd"), // reviewed · Exclusive/StoneGolem.gd
  "thorn_shortbow": stub("thorn_shortbow", "on_hit", "poison_weapon"), // reviewed · Exclusive/ThornShortbow.gd
  "thorn_whip": stub("thorn_whip", "on_hit", "basic_cd"), // reviewed · ThornWhip.gd
  "thornbloom": stub("thornbloom", "on_hit", "basic_cd"), // reviewed · Exclusive/Thornbloom.gd
  "thors_hammer": stub("thors_hammer", "on_hit", "basic_cd"), // reviewed · Exclusive/ThorsHammer.gd
  "thunder_drake": stub("thunder_drake", "on_hit", "basic_cd"), // reviewed · Exclusive/ThunderDrake.gd
  "torch": stub("torch", "on_hit", "basic_cd"), // reviewed · Torch.gd
  "war_scythe": stub("war_scythe", "on_hit", "basic_cd"), // reviewed · Exclusive/WarScythe.gd
  "water_elemental": stub("water_elemental", "on_hit", "basic_cd"), // reviewed · Exclusive/WaterElemental.gd
  "wrench": stub("wrench", "on_hit", "basic_cd"), // reviewed · Exclusive/Wrench.gd
};
