/**
 * GENERATED by scripts/gen-sim-dedicated-ports.mjs — do not hand-edit.
 * Raise fidelity via scripts/ports.js + registry REVIEWED, then re-run generator.
 */

import { HANDLERS } from '../handlers.js';

/** @param {string} id @param {string} family @param {string} template */
function stub(id, family, template) {
  const base = HANDLERS[template] || HANDLERS.basic_cd;
  return {
    handlerId: id,
    family,
    onCombatStart: base.onCombatStart,
    onCooldownEffect: base.onCooldownEffect,
  };
}

/** Band M — Synergy auras: synergy_aura (44 items) */
/** @type {Record<string, import('../handlers.js').ScriptHandler>} */
export const HANDLERS_M = {
  "amulet_of_agility": stub("amulet_of_agility", "synergy_aura", "empower_aura"), // reviewed · Exclusive/AmuletofAgility.gd
  "amulet_of_alchemy": stub("amulet_of_alchemy", "synergy_aura", "empower_aura"), // reviewed · Exclusive/AmuletofAlchemy.gd
  "amulet_of_steel": stub("amulet_of_steel", "synergy_aura", "empower_aura"), // reviewed · Exclusive/AmuletofSteel.gd
  "angel_crystal": stub("angel_crystal", "synergy_aura", "empower_aura"), // reviewed · Exclusive/AngelCrystal.gd
  "bionic_armor": stub("bionic_armor", "synergy_aura", "empower_aura"), // reviewed · Exclusive/BionicArmor.gd
  "burning_spikes": stub("burning_spikes", "synergy_aura", "empower_aura"), // reviewed · Exclusive/BurningSpikes.gd
  "burning_torch": stub("burning_torch", "synergy_aura", "empower_aura"), // reviewed · BurningTorch.gd
  "cap_of_brilliance": stub("cap_of_brilliance", "synergy_aura", "empower_aura"), // reviewed · Exclusive/CapofBrilliance.gd
  "crossblades": stub("crossblades", "synergy_aura", "empower_aura"), // reviewed · Crossblades.gd
  "cursed_hair_comb": stub("cursed_hair_comb", "synergy_aura", "empower_aura"), // reviewed · CursedHairComb.gd
  "deck_of_cards": stub("deck_of_cards", "synergy_aura", "empower_aura"), // reviewed · DeckofCards.gd
  "dragon_nest": stub("dragon_nest", "synergy_aura", "empower_aura"), // reviewed · Exclusive/DragonNest.gd
  "falcon_blade": stub("falcon_blade", "synergy_aura", "empower_aura"), // reviewed · FalconBlade.gd
  "fedora": stub("fedora", "synergy_aura", "empower_aura"), // reviewed · Exclusive/Fedora.gd
  "gingerbread_man": stub("gingerbread_man", "synergy_aura", "empower_aura"), // reviewed · GingerbreadMan.gd
  "gloves_of_haste": stub("gloves_of_haste", "synergy_aura", "empower_aura"), // reviewed · GlovesofHaste.gd
  "hardwood": stub("hardwood", "synergy_aura", "empower_aura"), // reviewed · Exclusive/Hardwood.gd
  "hero_longsword": stub("hero_longsword", "synergy_aura", "empower_aura"), // reviewed · HeroLongsword.gd
  "hero_shield": stub("hero_shield", "synergy_aura", "empower_aura"), // reviewed · Exclusive/HeroShield.gd
  "hero_sword": stub("hero_sword", "synergy_aura", "empower_aura"), // reviewed · HeroSword.gd
  "inner_power": stub("inner_power", "synergy_aura", "empower_aura"), // reviewed · Exclusive/InnerPower.gd
  "lucky_piggy": stub("lucky_piggy", "synergy_aura", "empower_aura"), // reviewed · LuckyPiggy.gd
  "magic_badge": stub("magic_badge", "synergy_aura", "empower_aura"), // reviewed · Exclusive/MagicBadge.gd
  "magic_ring": stub("magic_ring", "synergy_aura", "empower_aura"), // reviewed · Exclusive/MagicRing.gd
  "more_stats": stub("more_stats", "synergy_aura", "empower_aura"), // reviewed · Exclusive/MoreStats.gd
  "mushroom_farm": stub("mushroom_farm", "synergy_aura", "empower_aura"), // reviewed · Exclusive/MushroomFarm.gd
  "oil_lamp": stub("oil_lamp", "synergy_aura", "empower_aura"), // reviewed · Exclusive/OilLamp.gd
  "portable_altar": stub("portable_altar", "synergy_aura", "empower_aura"), // reviewed · Exclusive/PortableAltar.gd
  "puzzlebag_l": stub("puzzlebag_l", "synergy_aura", "empower_aura"), // reviewed · Exclusive/PuzzlebagL.gd
  "rainbow_orb": stub("rainbow_orb", "synergy_aura", "empower_aura"), // reviewed · Exclusive/RainbowOrb.gd
  "rat_chef": stub("rat_chef", "synergy_aura", "empower_aura"), // reviewed · Exclusive/RatChef.gd
  "scholar_bag": stub("scholar_bag", "synergy_aura", "empower_aura"), // reviewed · Exclusive/ScholarBag.gd
  "shepherds_crook": stub("shepherds_crook", "synergy_aura", "empower_aura"), // reviewed · Exclusive/ShepherdsCrook.gd
  "sloth": stub("sloth", "synergy_aura", "empower_aura"), // reviewed · Exclusive/Sloth.gd
  "smithing_for_dummies": stub("smithing_for_dummies", "synergy_aura", "empower_aura"), // reviewed · Exclusive/SmithingForDummies.gd
  "spring_loader": stub("spring_loader", "synergy_aura", "empower_aura"), // reviewed · Exclusive/SpringLoader.gd
  "steel_dragon": stub("steel_dragon", "synergy_aura", "empower_aura"), // reviewed · Exclusive/SteelDragon.gd
  "stone_armor": stub("stone_armor", "synergy_aura", "empower_aura"), // reviewed · Exclusive/StoneArmor.gd
  "stone_gloves": stub("stone_gloves", "synergy_aura", "empower_aura"), // reviewed · Exclusive/StoneGloves.gd
  "thorn_bow": stub("thorn_bow", "synergy_aura", "empower_aura"), // reviewed · ThornBow.gd
  "time_melting": stub("time_melting", "synergy_aura", "empower_aura"), // reviewed · Exclusive/TimeMelting.gd
  "toolbox": stub("toolbox", "synergy_aura", "empower_aura"), // reviewed · Exclusive/Toolbox.gd
  "whetstone": stub("whetstone", "synergy_aura", "empower_aura"), // reviewed · Whetstone.gd
  "yggdrasil_leaf": stub("yggdrasil_leaf", "synergy_aura", "empower_aura"), // reviewed · YggdrasilLeaf.gd
};
