/**
 * GENERATED by scripts/gen-sim-dedicated-ports.mjs — do not hand-edit.
 * Raise fidelity via scripts/ports.js + registry REVIEWED, then re-run generator.
 */

import { HANDLERS_I } from './band-i-weapons.js';
import { HANDLERS_J } from './band-j-onhit.js';
import { HANDLERS_K } from './band-k-custom-am.js';
import { HANDLERS_L } from './band-l-custom-nz.js';
import { HANDLERS_M } from './band-m-auras.js';
import { HANDLERS_N } from './band-n-start-pets.js';
import { HANDLERS_O } from './band-o-uniques.js';

/** @type {Record<string, import('../handlers.js').ScriptHandler>} */
export const DEDICATED_HANDLERS = {
  ...HANDLERS_I,
  ...HANDLERS_J,
  ...HANDLERS_K,
  ...HANDLERS_L,
  ...HANDLERS_M,
  ...HANDLERS_N,
  ...HANDLERS_O,
};

export function listDedicatedIds() {
  return Object.keys(DEDICATED_HANDLERS);
}
