import fs from 'fs';

const env = Object.fromEntries(
  fs.readFileSync('.env', 'utf8').split(/\r?\n/)
    .filter((l) => l && !l.trim().startsWith('#') && l.includes('='))
    .map((l) => {
      const i = l.indexOf('=');
      return [l.slice(0, i).trim(), l.slice(i + 1).trim()];
    }),
);

const url = env.SUPABASE_PROJECT_URL;
const key = env.SUPABASE_PUBLISHABLE_KEY;
if (!url || !key) {
  console.error('Need SUPABASE_PROJECT_URL and SUPABASE_PUBLISHABLE_KEY in .env');
  process.exit(1);
}

const submitSecret = env.BPB_SUBMIT_SECRET || '';
const baseFn = `${url.replace(/\/$/, '')}/functions/v1`;
const submitBuildUrl = `${baseFn}/submit-build`;
const adminBuildsUrl = `${baseFn}/admin-builds`;
const voteBuildUrl = `${baseFn}/vote-build`;

const out = `/**
 * Auto-generated by scripts/write-config.mjs — do not commit.
 */
export const config = {
  supabaseUrl: ${JSON.stringify(url)},
  supabasePublishableKey: ${JSON.stringify(key)},
  submitBuildUrl: ${JSON.stringify(submitBuildUrl)},
  adminBuildsUrl: ${JSON.stringify(adminBuildsUrl)},
  voteBuildUrl: ${JSON.stringify(voteBuildUrl)},
  submitSecret: ${JSON.stringify(submitSecret)},
};
`;

fs.writeFileSync('js/shared/config.js', out);
console.log('wrote js/shared/config.js');
if (!submitSecret) {
  console.warn(
    'Note: BPB_SUBMIT_SECRET missing — create Submit and /admin/ will stay blocked until set.',
  );
}
