import fs from 'fs';

const env = Object.fromEntries(
  fs.readFileSync('.env', 'utf8').split(/\r?\n/)
    .filter((l) => l && !l.trim().startsWith('#') && l.includes('='))
    .map((l) => {
      const i = l.indexOf('=');
      return [l.slice(0, i).trim(), l.slice(i + 1).trim()];
    }),
);

const url = env.SUPABASE_PROJECT_URL;
const key = env.SUPABASE_PUBLISHABLE_KEY;
if (!url || !key) {
  console.error('Need SUPABASE_PROJECT_URL and SUPABASE_PUBLISHABLE_KEY in .env');
  process.exit(1);
}

const baseFn = `${url.replace(/\/$/, '')}/functions/v1`;
const submitBuildUrl = `${baseFn}/submit-build`;
const adminBuildsUrl = `${baseFn}/admin-builds`;
const adminReportsUrl = `${baseFn}/admin-reports`;
const siteAccessUrl = `${baseFn}/site-access`;
const voteBuildUrl = `${baseFn}/vote-build`;
const createCheckoutUrl = `${baseFn}/create-checkout`;
const createPortalUrl = `${baseFn}/create-portal`;
const reportSimUrl = `${baseFn}/report-sim`;
const screenshotToBuildUrl = `${baseFn}/screenshot-to-build`;
const discordGuildUrl = `${baseFn}/discord-guild`;
const cosmeticCatalogUrl = `${baseFn}/cosmetic-catalog`;
const cosmeticSubmissionsUrl = `${baseFn}/cosmetic-submissions`;
const eventWinnerUrl = `${baseFn}/event-winner`;
const siteAccessMode = String(env.BPB_SITE_ACCESS_MODE || 'live').toLowerCase() === 'private'
  ? 'private'
  : 'live';

const out = `/**
 * Auto-generated by scripts/write-config.mjs — do not commit.
 */
export const config = {
  siteAccessMode: ${JSON.stringify(siteAccessMode)},
  supabaseUrl: ${JSON.stringify(url)},
  supabasePublishableKey: ${JSON.stringify(key)},
  submitBuildUrl: ${JSON.stringify(submitBuildUrl)},
  adminBuildsUrl: ${JSON.stringify(adminBuildsUrl)},
  adminReportsUrl: ${JSON.stringify(adminReportsUrl)},
  siteAccessUrl: ${JSON.stringify(siteAccessUrl)},
  voteBuildUrl: ${JSON.stringify(voteBuildUrl)},
  createCheckoutUrl: ${JSON.stringify(createCheckoutUrl)},
  createPortalUrl: ${JSON.stringify(createPortalUrl)},
  reportSimUrl: ${JSON.stringify(reportSimUrl)},
  screenshotToBuildUrl: ${JSON.stringify(screenshotToBuildUrl)},
  discordGuildUrl: ${JSON.stringify(discordGuildUrl)},
  cosmeticCatalogUrl: ${JSON.stringify(cosmeticCatalogUrl)},
  cosmeticSubmissionsUrl: ${JSON.stringify(cosmeticSubmissionsUrl)},
  eventWinnerUrl: ${JSON.stringify(eventWinnerUrl)},
};
`;

fs.writeFileSync('js/shared/config.js', out);
console.log('wrote js/shared/config.js (server secrets are never published)');
